# Project 2: Cleaning and Analyzing Untidy Data

For this project, I'll be working with three different datasets and using pandas to clean and organize them. I'll also analyze the data to see what patterns I can find.

# 
Dataset 1: Clothing Sales


For my first dataset, I used monthly sales for five clothing categories. I'll create a CSV file, load it into pandas, and reorganize it to make comparisons easier.

In [6]:
import pandas as pd

clothing = {
    'Product': ['Jeans', 'Dresses', 'Sweaters', 'Skirts', 'Jackets'],
    'Jan': [120, 85, 175, 70, 200],
'Feb': [145, 110, 140, 90, 170],
'Mar': [160, 150, 95, 125, None]
    
}


df = pd.DataFrame(clothing)
df.to_csv('clothing_sales.csv', index=False)

df

    Product  Jan  Feb    Mar
0     Jeans  120  145  160.0
1   Dresses   85  110  150.0
2  Sweaters  175  140   95.0
3    Skirts   70   90  125.0
4   Jackets  200  170    NaN

In [7]:
df = pd.read_csv('clothing_sales.csv')


df

    Product  Jan  Feb    Mar
0     Jeans  120  145  160.0
1   Dresses   85  110  150.0
2  Sweaters  175  140   95.0
3    Skirts   70   90  125.0
4   Jackets  200  170    NaN

# 
Checking for Missing Values

Before cleaning, I want to check if any sales values are missing.

In [8]:
df.isnull().sum()

Product    0
Jan        0
Feb        0
Mar        1
dtype: int64

# Reshaping the Data

Right now, each month has its own column. I'll use melt() to put all the months into one column and their sales into another. This should make it easier to compare sales across categories.

In [9]:
clothing_tidy = pd.melt(
    df,
    id_vars=['Product'],
    var_name='Month',
    value_name='Sales'
    
)

clothing_tidy

     Product Month  Sales
0      Jeans   Jan  120.0
1    Dresses   Jan   85.0
2   Sweaters   Jan  175.0
3     Skirts   Jan   70.0
4    Jackets   Jan  200.0
5      Jeans   Feb  145.0
6    Dresses   Feb  110.0
7   Sweaters   Feb  140.0
8     Skirts   Feb   90.0
9    Jackets   Feb  170.0
10     Jeans   Mar  160.0
11   Dresses   Mar  150.0
12  Sweaters   Mar   95.0
13    Skirts   Mar  125.0
14   Jackets   Mar    NaN

# Handling Missing Data

The March sales for Jackets are missing. Since I don't know the actual value, I'll remove that row so it doesn't affect my analysis.

In [10]:
clothing_tidy = clothing_tidy.dropna()

clothing_tidy

     Product Month  Sales
0      Jeans   Jan  120.0
1    Dresses   Jan   85.0
2   Sweaters   Jan  175.0
3     Skirts   Jan   70.0
4    Jackets   Jan  200.0
5      Jeans   Feb  145.0
6    Dresses   Feb  110.0
7   Sweaters   Feb  140.0
8     Skirts   Feb   90.0
9    Jackets   Feb  170.0
10     Jeans   Mar  160.0
11   Dresses   Mar  150.0
12  Sweaters   Mar   95.0
13    Skirts   Mar  125.0

# Total Sales by Category


Now that the data is organized, I'll add up the sales for each clothing category to see which one performed the best.

In [11]:
category_sales = clothing_tidy.groupby('Product')['Sales'].sum()

category_sales

Product
Dresses     345.0
Jackets     370.0
Jeans       425.0
Skirts      285.0
Sweaters    410.0
Name: Sales, dtype: float64

# Total Sales by Month

Next, I'll add up the sales for each month to see which month had the highest overall sales.

In [12]:
monthly_sales = clothing_tidy.groupby('Month')['Sales'].sum()

monthly_sales

Month
Feb    655.0
Jan    650.0
Mar    530.0
Name: Sales, dtype: float64

# Conclusion

Jeans had the highest total sales with 425 dollars. February had the highest overall sales at 655, with January very close at 650. March had the lowest total, but the missing jacket sales may have affected that result.

# Dataset 2: NFL Quarterback Statistics (Dontae's)

This dataset shows passing yards and touchdowns for three quarterbacks from 2023 to 2025. The statistics are separated by year, so I'll reorganize the data to make it easier to compare their performance.

In [13]:
nfl = {
    'Quarterback': ['Patrick Mahomes', 'Josh Allen', 'Lamar Jackson'],
    'Yards_2023': [4183, 4306, 3678],
    'Yards_2024': [3928, 3731, 4172],
    'Yards_2025': [4587, 3668, 4050],
    'TDs_2023': [27, 29, 24],
    'TDs_2024': [26, 28, 41],
    'TDs_2025': [30, 25, 34]
}

nfl_df = pd.DataFrame(nfl)
nfl_df.to_csv('nfl_stats.csv', index=False)

nfl_df

,Quarterback,Yards_2023,Yards_2024,Yards_2025,TDs_2023,TDs_2024,TDs_2025
0,Patrick Mahomes,4183,3928,4587,27,26,30
1,Josh Allen,4306,3731,3668,29,28,25
2,Lamar Jackson,3678,4172,4050,24,41,34

# Loading the Data

I'll load the CSV into pandas and check the data before
reorganizing it.

In [16]:
nfl_df = pd.read_csv('nfl_stats.csv')

nfl_df

,Quarterback,Yards_2023,Yards_2024,Yards_2025,TDs_2023,TDs_2024,TDs_2025
0,Patrick Mahomes,4183,3928,4587,27,26,30
1,Josh Allen,4306,3731,3668,29,28,25
2,Lamar Jackson,3678,4172,4050,24,41,34

In [17]:
nfl_df.isnull().sum()

Quarterback    0
Yards_2023     0
Yards_2024     0
Yards_2025     0
TDs_2023       0
TDs_2024       0
TDs_2025       0
dtype: int64

# Reshaping the Data


The years are currently i
ncluded in the column names. I'll use melt() to put the statistics into a longer format, then separate the years from the types of statistics.

In [18]:
nfl_tidy = nfl_df.melt(
    id_vars='Quarterback',
    var_name='Statistic_Year',
    value_name='Value'
)

nfl_tidy[['Statistic', 'Year']] = nfl_tidy['Statistic_Year'].str.split('_', expand=True)

nfl_tidy = nfl_tidy.drop(columns='Statistic_Year')

nfl_tidy

        Quarterback  Value Statistic  Year
0   Patrick Mahomes   4183     Yards  2023
1        Josh Allen   4306     Yards  2023
2     Lamar Jackson   3678     Yards  2023
3   Patrick Mahomes   3928     Yards  2024
4        Josh Allen   3731     Yards  2024
5     Lamar Jackson   4172     Yards  2024
6   Patrick Mahomes   4587     Yards  2025
7        Josh Allen   3668     Yards  2025
8     Lamar Jackson   4050     Yards  2025
9   Patrick Mahomes     27       TDs  2023
10       Josh Allen     29       TDs  2023
11    Lamar Jackson     24       TDs  2023
12  Patrick Mahomes     26       TDs  2024
13       Josh Allen     28       TDs  2024
14    Lamar Jackson     41       TDs  2024
15  Patrick Mahomes     30       TDs  2025
16       Josh Allen     25       TDs  2025
17    Lamar Jackson     34       TDs  2025

# Comparing Passing Yards

I'll compare the total passing 
yards for each quarterback across the three seasons.

In [19]:
passing_yards = nfl_tidy[nfl_tidy['Statistic'] == 'Yards']

passing_yards.groupby('Quarterback')['Value'].sum()

Quarterback
Josh Allen         11705
Lamar Jackson      11900
Patrick Mahomes    12698
Name: Value, dtype: int64

# Comparing Touchdowns

Next, I'll add up the touchdowns
for each quarterback to see who had the most across the three seasons.

In [20]:
touchdowns = nfl_tidy[nfl_tidy['Statistic'] == 'TDs']



touchdowns.groupby('Quarterback')['Value'].sum()

Quarterback
Josh Allen         82
Lamar Jackson      99
Patrick Mahomes    83
Name: Value, dtype: int64

# Conclusion


Patrick Mahomes had the most passing yards across the three seasons with 12,698. Lamar Jackson had the most touchdowns with 99. Looking at the results, more passing yards doesn't necessarily mean more touchdowns

## Dataset 3: Book Sales (Alyssa's)

This dataset shows monthly sales for five books at a small bookstore. Each month has its own column, so I'll reorganize the data to compare sales by book, genre, and month.

In [22]:
books = {
    'Book': ['The Last Summer', 'Midnight House', 'Lost in the Stars',
             'The Silent Case', 'Second Chances'],
    'Genre': ['Romance', 'Horror', 'Science Fiction',
              'Mystery', 'Romance'],
    'Jan': [45, 32, 27, 51, 39],
    'Feb': [52, 41, 35, 48, 44],
    'Mar': [61, 38, 46, 57, 50]
}

books_df = pd.DataFrame(books)
books_df.to_csv('book_sales.csv', index=False)

books_df

                Book            Genre  Jan  Feb  Mar
0    The Last Summer          Romance   45   52   61
1     Midnight House           Horror   32   41   38
2  Lost in the Stars  Science Fiction   27   35   46
3    The Silent Case          Mystery   51   48   57
4     Second Chances          Romance   39   44   50

# Loading the Data

I'll read the CSV into pandas and check for missing values before cleaning it.

In [23]:
books_df = pd.read_csv('book_sales.csv')

books_df

                Book            Genre  Jan  Feb  Mar
0    The Last Summer          Romance   45   52   61
1     Midnight House           Horror   32   41   38
2  Lost in the Stars  Science Fiction   27   35   46
3    The Silent Case          Mystery   51   48   57
4     Second Chances          Romance   39   44   50

In [24]:
books_df.isnull().sum()

Book     0
Genre    0
Jan      0
Feb      0
Mar      0
dtype: int64

# Reshaping the Data


The sales are spread across three monthly columns. I'll use melt() to put the months into one column and the sales into another.

In [25]:
books_tidy = books_df.melt(
    id_vars=['Book', 'Genre'],
    var_name='Month',
    value_name='Sales'
)

books_tidy

                 Book            Genre Month  Sales
0     The Last Summer          Romance   Jan     45
1      Midnight House           Horror   Jan     32
2   Lost in the Stars  Science Fiction   Jan     27
3     The Silent Case          Mystery   Jan     51
4      Second Chances          Romance   Jan     39
5     The Last Summer          Romance   Feb     52
6      Midnight House           Horror   Feb     41
7   Lost in the Stars  Science Fiction   Feb     35
8     The Silent Case          Mystery   Feb     48
9      Second Chances          Romance   Feb     44
10    The Last Summer          Romance   Mar     61
11     Midnight House           Horror   Mar     38
12  Lost in the Stars  Science Fiction   Mar     46
13    The Silent Case          Mystery   Mar     57
14     Second Chances          Romance   Mar     50

# Total Sales by Book

I'll add up each book's sales to see which title sold the most over the three months.

In [26]:
book_totals = books_tidy.groupby('Book')['Sales'].sum()

book_totals

Book
Lost in the Stars    108
Midnight House       111
Second Chances       133
The Last Summer      158
The Silent Case      156
Name: Sales, dtype: int64

# Sales by Genre

Next, I'll compare
the genres to see which one had the highest total sales.

In [27]:
genre_totals = books_tidy.groupby('Genre')['Sales'].sum()

genre_totals

Genre
Horror             111
Mystery            156
Romance            291
Science Fiction    108
Name: Sales, dtype: int64

# Monthly Sales

I'll also compare the total sales for each month to see if sales increased or decreased over time.

In [28]:
book_monthly = books_tidy.groupby('Month')['Sales'].sum()

book_monthly

Month
Feb    220
Jan    194
Mar    252
Name: Sales, dtype: int64

# Conclusion

The Last Summer had the highest total sales with 158 books sold. Romance was the most popular genre overall, with 291 books sold. March had the highest sales at 252.