# Week 5 Assignment

In this assignment, I will use Python and pandas to analyze airport and weather data. I will also verify my results and check for any outliers that may lead to false answers

In [3]:
import pandas as pd

In [2]:
airports = pd.read_csv("airports.csv")
airports.head()

,faa,name,lat,lon,alt,tz,dst,tzone
0,04G,Lansdowne Airport,41.130472,-80.619583,1044,-5,A,America/New_York
1,06A,Moton Field Municipal Airport,32.460572,-85.680028,264,-6,A,America/Chicago
2,06C,Schaumburg Regional,41.989341,-88.101243,801,-6,A,America/Chicago
3,06N,Randall Airport,41.431912,-74.391561,523,-5,A,America/New_York
4,09J,Jekyll Island Airport,31.074472,-81.427778,11,-5,A,America/New_York

## Question 1: What is the northernmost airport in the United States?

I will start by looking at the five airports with the highest latitude.

In [3]:
airports.sort_values("lat", ascending=False).head()

,faa,name,lat,lon,alt,tz,dst,tzone
417,EEN,Dillant Hopkins Airport,72.270833,42.898333,149,-5,A,NaN
230,BRW,Wiley Post Will Rogers Mem,71.285446,-156.766003,44,-9,A,America/Anchorage
110,AIN,Wainwright Airport,70.638056,-159.994722,41,-9,A,America/Anchorage
708,K03,Wainwright As,70.613378,-159.860350,35,-9,A,America/Anchorage
152,ATK,Atqasuk Edward Burnell Sr Memorial Airport,70.467300,-157.436000,96,-9,A,America/Anchorage

The data lists Dillant Hopkins Airport as having the highest latitude. However, looking at the rest of the longitudes for the other aiports, the coordinates for Dillant seems off. Im going to google to see if these coordinates are correct.

I found that the coordinates for Dillant Hopkins Airport are incorrect in the dataset. Research shows that the airport is in Keene, New Hampshire at about 42.90° N and 72.27° W. The latitude and longitude in the dataset appear to be switched, so I will not use this airport as the northernmost result.

In [4]:
airports[airports["faa"] != "EEN"].sort_values("lat", ascending=False).head()

,faa,name,lat,lon,alt,tz,dst,tzone
230,BRW,Wiley Post Will Rogers Mem,71.285446,-156.766003,44,-9,A,America/Anchorage
110,AIN,Wainwright Airport,70.638056,-159.994722,41,-9,A,America/Anchorage
708,K03,Wainwright As,70.613378,-159.860350,35,-9,A,America/Anchorage
152,ATK,Atqasuk Edward Burnell Sr Memorial Airport,70.467300,-157.436000,96,-9,A,America/Anchorage
1363,UUK,Ugnu-Kuparuk Airport,70.330833,-149.597500,67,-9,A,America/Anchorage

After removing the incorrect Dillant Hopkins Airport result, Wiley Post-Will Rogers Memorial Airport in Utqiaġvik, Alaska has the highest latitude in the data at about 71.29° N. Based on my research, this result is consistent with its location in northern Alaska.

Answer: Wiley Post-Will Rogers Memorial Airport - BRW

## Question 2: What is the easternmost airport in the United States?

I will start by looking at the five airports with the highest longitude.

In [5]:
airports.sort_values("lon", ascending=False).head()

,faa,name,lat,lon,alt,tz,dst,tzone
1290,SYA,Eareckson As,52.712275,174.113620,98,-9,A,America/Anchorage
942,MYF,Montgomery Field,32.475900,117.759000,17,8,A,Asia/Chongqing
396,DVT,Deer Valley Municipal Airport,33.411700,112.457000,1478,8,A,Asia/Chongqing
417,EEN,Dillant Hopkins Airport,72.270833,42.898333,149,-5,A,NaN
444,EPM,Eastport Municipal Airport,44.910111,-67.012694,45,-5,A,America/New_York

Some of these results don't look right. Montgomery Field and Deer Valley are both in the western U.S., so their positive longitude values are wrong. Dillant Hopkins also has the coordinate issue I found earlier. Eareckson Air Station is in Alaska, so I need to look into that one more before deciding on the easternmost airport.

In [6]:
airports.sort_values("lon").head()

,faa,name,lat,lon,alt,tz,dst,tzone
95,ADK,Adak Airport,51.878000,-176.646000,18,-9,A,America/Anchorage
112,AKB,Atka Airport,52.220278,-174.206389,56,-9,A,America/Anchorage
522,GAM,Gambell Airport,63.766800,-171.733000,27,-9,A,America/Anchorage
1281,SVA,Savoonga Airport,63.686400,-170.493000,53,-9,A,America/Anchorage
1251,SNP,St Paul Island,57.167333,-170.220444,63,-9,A,America/Anchorage

I checked Eareckson Air Station and confirmed that it is in Shemya, Alaska at about 174.11° E. This matches the longitude in the dataset, so unlike some of the other results, this value is not an error.

Answer to question 2 : Eareckson Air Station - SYA

## Question 3: On February 12, 2013, which New York area airport had the windiest weather?

I will use the weather data to compare wind speeds at the New York area airports on this date.

In [4]:
weather = pd.read_csv("weather.csv")
weather.head()

,origin,year,month,day,hour,temp,dewp,humid,wind_dir,wind_speed,wind_gust,precip,pressure,visib,time_hour
0,EWR,2013,1,1,1,39.02,26.06,59.37,270.0,10.35702,NaN,0.0,1012.0,10.0,2013-01-01T06:00:00Z
1,EWR,2013,1,1,2,39.02,26.96,61.63,250.0,8.05546,NaN,0.0,1012.3,10.0,2013-01-01T07:00:00Z
2,EWR,2013,1,1,3,39.02,28.04,64.43,240.0,11.50780,NaN,0.0,1012.5,10.0,2013-01-01T08:00:00Z
3,EWR,2013,1,1,4,39.92,28.04,62.21,250.0,12.65858,NaN,0.0,1012.2,10.0,2013-01-01T09:00:00Z
4,EWR,2013,1,1,5,39.02,28.04,64.43,260.0,12.65858,NaN,0.0,1011.9,10.0,2013-01-01T10:00:00Z

In [5]:
feb12 = weather[
    (weather["year"] == 2013) &
    (weather["month"] == 2) &
    (weather["day"] == 12)
]

feb12

,origin,year,month,day,hour,temp,dewp,humid,wind_dir,wind_speed,wind_gust,precip,pressure,visib,time_hour
1006,EWR,2013,2,12,0,39.92,39.02,96.55,240.0,6.90468,NaN,0.0,1006.9,10.0,2013-02-12T05:00:00Z
1007,EWR,2013,2,12,1,39.92,37.94,92.56,250.0,9.20624,NaN,0.0,1007.2,10.0,2013-02-12T06:00:00Z
1008,EWR,2013,2,12,2,39.92,28.04,62.21,270.0,20.71404,25.31716,0.0,1007.8,10.0,2013-02-12T07:00:00Z
1009,EWR,2013,2,12,3,39.02,26.96,61.63,260.0,1048.36058,NaN,0.0,1008.3,10.0,2013-02-12T08:00:00Z
1010,EWR,2013,2,12,4,39.02,26.96,64.29,280.0,12.65858,NaN,0.0,1008.8,10.0,2013-02-12T09:00:00Z
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
18434,LGA,2013,2,12,19,41.00,21.92,46.23,260.0,14.96014,21.86482,0.0,1014.7,10.0,2013-02-13T00:00:00Z
18435,LGA,2013,2,12,20,39.92,23.00,50.46,290.0,10.35702,NaN,0.0,1013.6,10.0,2013-02-13T01:00:00Z
18436,LGA,2013,2,12,21,39.02,21.92,49.93,310.0,10.35702,NaN,0.0,1012.8,10.0,2013-02-13T02:00:00Z
18437,LGA,2013,2,12,22,39.02,23.00,52.26,310.0,11.50780,NaN,0.0,1012.7,10.0,2013-02-13T03:00:00Z
18438,LGA,2013,2,12,23,37.94,23.00,54.51,300.0,9.20624,NaN,0.0,1013.5,10.0,2013-02-13T04:00:00Z

In [6]:
feb12.sort_values("wind_speed", ascending=False).head(10)

,origin,year,month,day,hour,temp,dewp,humid,wind_dir,wind_speed,wind_gust,precip,pressure,visib,time_hour
1009,EWR,2013,2,12,3,39.02,26.96,61.63,260.0,1048.36058,NaN,0.0,1008.3,10.0,2013-02-12T08:00:00Z
18417,LGA,2013,2,12,2,42.98,26.06,50.94,290.0,23.01560,31.07106,0.0,1007.1,10.0,2013-02-12T07:00:00Z
18428,LGA,2013,2,12,13,44.06,23.00,43.02,300.0,21.86482,25.31716,0.0,1011.7,10.0,2013-02-12T18:00:00Z
1018,EWR,2013,2,12,12,44.06,26.06,48.87,270.0,21.86482,31.07106,0.0,1012.5,10.0,2013-02-12T17:00:00Z
9717,JFK,2013,2,12,8,42.08,24.08,48.56,280.0,20.71404,27.61872,0.0,1011.6,10.0,2013-02-12T13:00:00Z
18429,LGA,2013,2,12,14,44.06,23.00,43.02,300.0,20.71404,25.31716,0.0,1011.5,10.0,2013-02-12T19:00:00Z
1008,EWR,2013,2,12,2,39.92,28.04,62.21,270.0,20.71404,25.31716,0.0,1007.8,10.0,2013-02-12T07:00:00Z
9716,JFK,2013,2,12,7,39.92,26.06,57.33,270.0,19.56326,NaN,0.0,1010.9,10.0,2013-02-12T12:00:00Z
18416,LGA,2013,2,12,1,44.06,30.92,59.64,270.0,19.56326,28.76950,0.0,1006.6,10.0,2013-02-12T06:00:00Z
18427,LGA,2013,2,12,12,44.06,23.00,43.02,270.0,19.56326,26.46794,0.0,1011.8,10.0,2013-02-12T17:00:00Z

There is a wind speed of 1048.36 mph for EWR, which is clearly an outlier and not a realistic wind speed. I will remove this value before comparing the airports.

In [8]:
feb12_clean = feb12[feb12["wind_speed"] < 100]

feb12_clean.groupby("origin")["wind_speed"].max()

origin
EWR    21.86482
JFK    20.71404
LGA    23.01560
Name: wind_speed, dtype: float64

After removing the EWR outlier, I compared the highest wind speeds for each airport. LGA had the highest wind speed at about 23.02 mph.

Answer: LaGuardia Airport - LGA